# Generated by Django 4.2.7 on 2023-11-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
